# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches: 
    include:
    - master
  paths:
    exclude:
    - master/EHMessageGenerator
    - master/EHMessageReader

# Set variables 
variables:
  resourceGroupName: 'Mythical-EH-ASA-EH-AF_RG'
  location: 'EastUS'
  ehNamespace: 'mythicalairlineshub'
  ingestionEventhub: 'members'
  egressEventhub: 'membersagg'
  partitionCount: 12



pool:
  vmImage: 'ubuntu-latest'

steps:

# Build Java Function EHMessageTrigger
- task: Maven@3
  inputs:
    mavenPomFile: 'EHMessageTrigger/pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    mavenVersionOption: 'Default'
    mavenOptions: '-Xmx3072m'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'latest'


# Establish Azure Resources
# Resource Group
# Function App
# Event Hub
# Azure resource group deployment
# Deploy an Azure Resource Manager (ARM) template to a resource group and manage virtual machines
- task: AzureCLI@2
  inputs:
    azureSubscription: 'JAPADMAN Lab(881ac365-d417-4791-b2a9-48789acbb88d)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 


- task: AzureCLI@2
  inputs:
    azureSubscription: 'JAPADMAN Lab(881ac365-d417-4791-b2a9-48789acbb88d)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az group create --name $resourceGroupName --location $location'








# ...
# Release Azure Function
- task: CopyFiles@2
  displayName: Copy Files
  inputs:
    SourceFolder: $(system.defaultworkingdirectory)/EHMessageTrigger/target/azure-functions/
    Contents: '**'
    TargetFolder: $(build.artifactstagingdirectory)   


- task: PublishBuildArtifacts@1
  displayName: Publish Artifact
  inputs:
    PathtoPublish: $(build.artifactstagingdirectory)    

- task: AzureFunctionApp@1
  displayName: Azure Function App deploy
  inputs:
    azureSubscription: $(serviceConnectionToAzure)
    appType: functionApp
    appName: $(appName)
    package: $(build.artifactstagingdirectory)